[phases.setup]
nixPkgs = ["python312", "gcc", "postgresql"]

[phases.install]
cmds = ["python -m venv /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"]

[phases.build]
cmds = ["BUILD_PHASE=true cd NomoFlow && python manage.py collectstatic --noinput"]

[start]
cmd = "cd NomoFlow && gunicorn NomoFlow.wsgi:application --bind 0.0.0.0:$PORT"
