[build]
builder = "nixpacks"
buildCommand = "cd NomoFlow && python manage.py collectstatic --noinput"

[deploy]
startCommand = "cd NomoFlow && python manage.py migrate --noinput && gunicorn NomoFlow.wsgi:application --bind 0.0.0.0:$PORT"
healthcheckPath = "/health/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
